apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: x-travels
  name: x-travels
spec:
  replicas: 3
  selector:
    matchLabels:
      app: x-travels
  template:
    metadata:
      labels:
        app: x-travels
    spec:
      containers:
      - image: xiejuntao/x-travel
        name: x-travels
